### ISSUE TITLE
[❓] link to latest Pterodactyl Egg script

### ISSUE THREAD

**Issue by Wunderharke** [jeakfrw/jeak-framework#71]
Hey guys,

first I want to say this is a fantastic project!

However I did not manage to find a link to the lastest Pterodactyl Egg Script,
I found the GitLab link in the docs but the target repository isn't available anymore.
Now I want to kindly ask you to update the link or point me to the script with an answere here.

Thank you!

**Comment by MarkTwoFive** [comment]
Hi there,
glad to hear that :slightly_smiling_face: 

The Pterodactyl image moved to GitHub together with the project and is available via: https://github.com/jeakfrw/pterodactyl-image (the JSON file is in the repository too).  
It seems I forgot that particular link when I went through updating all the references :sweat_smile: Thank you for bringing this up, I'll quickly fix that!  
  
If you encounter any issues with the egg, feel free to tell us too. :+1:

**Comment by MarkTwoFive** [comment]
// docs updated :v:

**Comment by Wunderharke** [comment]
Thanks for the link, installation worked!
However, I run into some other problems...
I'm not able to connect to a database created via Panel (Connection refused) right now.
I'll try to figure it out myself 😅 and report later.

**Comment by MarkTwoFive** [comment]
I can help you with that too if you want to as we're using Pterodactyl internally.

**Comment by Wunderharke** [comment]
I could indeed need some help ... 😅 
I always get "Connection refused" when I try to connect to the database.
![Databases](https://user-images.githubusercontent.com/5105672/62213897-43804900-b3a4-11e9-8205-303961f6a13e.png)

my json is like this:
```
{
  "host": "127.0.0.1",
  "port": "3306",
  "driver": "mariadb",
  "user": "XXXXXXXXXXXXXXX",
  "pass": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "schema": "s17_statistics",
  "dataSourceOpts": {
  }
}
```
Any ideas why this might happen?
Assume password and username is correct. While creating I set 127.0.0.1 as connection adress.
Thanks for your help!

**Comment by MarkTwoFive** [comment]
I might have an idea what the culprit is:  
> This should reflect the IP address that connections are allowed from. Uses standard MySQL notation. If unsure leave as ``%``.  
  
Pterodactyl docker containers do not connect from ``127.0.0.1`` since they are using the bridged ``pterodactyl_nw`` network. In addition, the ``127.0.0.1`` will also refer to the container the application is currently running in.  
My suggestion is: For you configuration files, use the hosts public IP as the ``host`` value and either set the "connections" value in Pterodactyl to ``%`` (which is a wildcard) or try the public IP of your host.  
  
Regarding security, there's not much concern as the traffic will be passed out of the bridge network but will never leave the interface of your host server as the system recognizes the target is the own machine.  
We - for example - have completely closed the database ports to the outside world and just use the wildcard internally.

**Comment by MarkTwoFive** [comment]
In addition: Some installations of MySQL / MariaDB will still have issues since they configured the database server to only listen to ``127.0.0.1`` by default which will ignore outside connections and those from docker networks. The solution there would be to re-configure the bind-address. :slightly_smiling_face:  
  
Oh, and in case that was too technical, feel free to hop into discord for a chat :wink:

**Comment by MarkTwoFive** [comment]
@Wunderharke were you able to solve your issue or can we assist you?

**Comment by MarkTwoFive** [comment]
Considering the lack of activity here, I would say this counts as resolved.  
If that is in fact not the case, feel free to re-open the issue.
